apiVersion: v1
kind: Namespace
metadata:
  name: sonar-quber
  labels:
    app: sonar-quber

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: sonar-quber
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql
      containers:
      - name: postgresql
        metadata:
          labels:
            app: postgresql
        image: harbor.chinauos.com/uos-container/postgresql:latest
        env:
          - name: POSTGRESQL_USER
            value: sonarqube
          - name: POSTGRESQL_PASSWORD
            value: sonarqube
          - name: POSTGRESQL_DATABASE
            value: sonarqube
        ports:
          - containerPort: 5432
            protocol: TCP
        resources: { }
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: postgresql-data
            mountPath: /var/lib/postgresql/data
          - name: postgresql
            mountPath: /var/lib/postgresql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarquber-deployment
  namespace: sonar-quber
spec:
  selector:
    matchLabels:
      app: sonar-quber
  template:
    metadata:
      labels:
        app: sonar-quber
    spec:
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: sonarqube-logs

      containers:
        - name: sonar-quber
          image: sonarqube:community
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: SONAR_JDBC_URL
              value: 'jdbc:postgresql://pgsql-service:5432/sonarqube'
            - name: SONAR_JDBC_USERNAME
              value: sonarqube
            - name: SONAR_JDBC_PASSWORD
              value: sonarqube
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: pgsql-service
  namespace: sonar-quber
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar-quber
  name: sonar-quber-service
  namespace: sonar-quber
spec:
  type: ClusterIP
  ports:
    - name: 9000-tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: sonar-quber
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sonarqube-route
  namespace: sonar-quber
  labels:
    app: sonar-quber
spec:
  host: sonarqube.utccp.com
  to:
    kind: Service
    name: sonar-quber-service
    weight: 100
  port:
    targetPort: 9000-tcp
  wildcardPolicy: None

