apiVersion: v1
kind: Namespace
metadata:
  name: my-web
  labels:
    app: http-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myWebPVC
  namespace: my-web
  labels:
    app: http-server
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: my-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      volumes:
        - name: http-server-logs
          persistentVolumeClaim:
           claimName: myWebPVC
      containers:
      - image: 'harbor.chinauos.com/tlj-test/http-server:v0.2'
        name: http-server
        ports:
        - containerPort: 8080

        volumeMounts:
          - mountPath: "/opt/log/nginx"
            name: http-server-logs
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-server
  name: http-server
  namespace: my-web
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: http-server
  type: LoadBalancer
