apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mysql
  namespace: mysql-example
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: managed-nfs-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-example
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:                        
        - name: MYSQL_ROOT_PASSWORD
          value: "123123"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: nfs-pvc-mysql
          mountPath: /var/lib/mysql         
          readOnly: false
      volumes:
      - name: nfs-pvc-mysql
        persistentVolumeClaim:
          claimName: nfs-pvc-mysql

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql-example
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32222
  selector:
    app: mysql

